export const CART_LIST_ITEM_REQUEST = 'CART_LIST_ITEM_REQUEST'
export const CART_LIST_ITEM_SUCCESS = 'CART_LIST_ITEM_SUCCESS'
export const CART_LIST_ITEM_FAIL = 'CART_LIST_ITEM_FAIL'
export const CART_LIST_RESET = 'CART_LIST_RESET'

export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST'
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS'
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL'

export const CART_UPDATE_ITEM_REQUEST = 'CART_UPDATE_ITEM_REQUEST'
export const CART_UPDATE_ITEM_SUCCESS = 'CART_UPDATE_ITEM_SUCCESS'
export const CART_UPDATE_ITEM_FAIL = 'CART_UPDATE_ITEM_FAIL'

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'

export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

export const CART_UPDATE_RESET = 'CART_UPDATE_RESET'
