export const ADD_PRODUCT_COMPARE_REQUEST = "ADD_PRODUCT_COMPARE_REQUEST";
export const ADD_PRODUCT_COMPARE_SUCCESS = "ADD_PRODUCT_COMPARE_SUCCESS";
export const ADD_PRODUCT_COMPARE_FAIL = "ADD PRODUCT_COMPARE_FAIL";

export const REMOVE_PRODUCT_COMPARE_REQUEST = "REMOVE_PRODUCT_COMPARE_REQUEST";
export const REMOVE_PRODUCT_COMPARE_SUCCESS = "REMOVE PRODUCT_COMPARE_SUCESS";
export const REMOVE_PRODUCT_COMPARE_FAIL = "REMOVE PRODUCT_COMPARE_FAIL";

export const REMOVE_ALL_PRODUCT_COMPARE_REQUEST =
  "REMOVE_ALL_PRODUCT_COMPARE_REQUEST";
export const REMOVE_ALL_PRODUCT_COMPARE_SUCCESS =
  "REMOVE_ALL PRODUCT_COMPARE_SUCESS";
export const REMOVE_ALL_PRODUCT_COMPARE_FAIL =
  "REMOVE_ALL PRODUCT_COMPARE_FAIL";

export const COMPARE_PRODUCT_REQUEST = "COMPARE_PRODUCT_REQUEST";
export const COMPARE_PRODUCT_SUCCESS = "COMPARE_PRODUCT_SUCESS";
export const COMPARE_PRODUCT_FAIL = "COMPARE_PRODUCT_FAIL";

export const COMPARE_PRODUCT_RESET = "COMPARE_PRODUCT_RESET";
