export const GET_PROVINCE_LIST_REQUEST = 'GET_PROVINCE_LIST_REQUEST'
export const GET_PROVINCE_LIST_SUCCESS = 'GET_PROVINCE_LIST_SUCCESS'
export const GET_PROVINCE_LIST_FAIL = 'GET_PROVINCE_LIST_FAIL'

export const GET_DISTRICT_LIST_REQUEST = 'GET_DISTRICT_LIST_REQUEST'
export const GET_DISTRICT_LIST_SUCCESS = 'GET_DISTRICT_LIST_SUCCESS'
export const GET_DISTRICT_LIST_FAIL = 'GET_DISTRICT_LIST_FAIL'

export const GET_WARD_LIST_REQUEST = 'GET_WARD_LIST_REQUEST'
export const GET_WARD_LIST_SUCCESS = 'GET_WARD_LIST_SUCCESS'
export const GET_WARD_LIST_FAIL = 'GET_WARD_LIST_FAIL'

export const CLEAR_ERROR_ADDRESS = 'CLEAR_ERROR_ADDRESS'

export const GET_SHIPPING_FEE_REQUEST = 'GET_SHIPPING_FEE_REQUEST'
export const GET_SHIPPING_FEE_SUCCESS = 'GET_SHIPPING_FEE_SUCCESS'
export const GET_SHIPPING_FEE_FAIL = 'GET_SHIPPING_FEE_FAIL'

export const CLEAR_ERROR = 'CLEAR_ERROR'
