export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_SEARCH_REQUEST = 'PRODUCT_SEARCH_REQUEST'
export const PRODUCT_SEARCH_SUCCESS = 'PRODUCT_SEARCH_SUCCESS'
export const PRODUCT_SEARCH_FAIL = 'PRODUCT_SEARCH_FAIL'

export const PRODUCT_LIST_BY_CATEGORY_REQUEST =
  'PRODUCT_LIST_BY_CATEGORY_REQUEST'
export const PRODUCT_LIST_BY_CATEGORY_SUCCESS =
  'PRODUCT_LIST_BY_CATEGORY_SUCCESS'
export const PRODUCT_LIST_BY_CATEGORY_FAIL = 'PRODUCT_LIST_BY_CATEGORY_FAIL'

export const PRODUCT_LIST_BY_SUB_CATEGORY_REQUEST =
  'PRODUCT_LIST_BY_SUB_CATEGORY_REQUEST'
export const PRODUCT_LIST_BY_SUB_CATEGORY_SUCCESS =
  'PRODUCT_LIST_BY_SUB_CATEGORY_SUCCESS'
export const PRODUCT_LIST_BY_SUB_CATEGORY_FAIL =
  'PRODUCT_LIST_BY_SUB_CATEGORY_FAIL'

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const PRODUCT_CREATE_COMMENT_REQUEST = 'PRODUCT_CREATE_COMMENT_REQUEST'
export const PRODUCT_CREATE_COMMENT_SUCCESS = 'PRODUCT_CREATE_COMMENT_SUCCESS'
export const PRODUCT_CREATE_COMMENT_FAIL = 'PRODUCT_CREATE_COMMENT_FAIL'
export const PRODUCT_CREATE_COMMENT_RESET = 'PRODUCT_CREATE_COMMENT_RESET'

export const PRODUCT_CREATE_REPLY_COMMENT_REQUEST =
  'PRODUCT_CREATE_REPLY_COMMENT_REQUEST'
export const PRODUCT_CREATE_REPLY_COMMENT_SUCCESS =
  'PRODUCT_CREATE_REPLY_COMMENT_SUCCESS'
export const PRODUCT_CREATE_REPLY_COMMENT_FAIL =
  'PRODUCT_CREATE_REPLY_COMMENT_FAIL'
export const PRODUCT_CREATE_REPLY_COMMENT_RESET =
  'PRODUCT_CREATE_REPLY_COMMENT_RESET'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

export const ADD_PRODUCT_TO_COMPARE = 'ADD_PRODUCT_TO_COMPARE'
export const REMOVE_PRODUCT_OUT_COMPARE = 'REMOVE_PRODUCT_OUT_COMPARE'
export const REMOVE_ALL_PRODUCTS_OUT_COMPARE = 'REMOVE_ALL_PRODUCTS_OUT_COMPARE'
export const COMPARE_PRODUCTS_REQUEST = 'COMPARE_PRODUCTS_REQUEST'
export const COMPARE_PRODUCTS_SUCCESS = 'COMPARE_PRODUCT_SUCCESS'
export const COMPARE_PRODUCTS_FAIL = 'COMPARE_PRODUCTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
